name: Build Todo

on:
  push:
    paths: ./Interfuse.Todo
    branches: [ "develop", "main" ]
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

permissions:
  pull-requests: read

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./Interfuse.Todo

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.12.1"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint pytest pytest-cov
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      - name: Test with pytest
        run: |
          pytest -v --cov --cov-report=xml --cov-report=html
      
      #- name: Analysing the code with pylint
      #  run: |
      #    pylint todo
      
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_TODO }}